version: '3.4'

services:
  nodemongodocker:
    image: nodemongodocker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    volumes: 
      - .:/usr/src/app
    # links: 
    #   - mongodb

  # mongodb:
  #   image: mongo:4.4.2
  #   ports: 
  #     - 27017:27017
  #   volumes: 
  #     - ./data:/data/db
    

volumes: 
  data: